_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: 'checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_all_30shot/model_final.pth'
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: "PseudoROIHeads"
    NUM_CLASSES: 80
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('coco_trainval_all_30shot',) #('coco_trainval_pseudo_30_thres06',) # ('coco_trainval_pseudo',)
  TEST: ('coco_test_all',)

SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.0001
  STEPS: (20000,)
  MAX_ITER: 60000  # 17.4 epoch
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 10

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 500
OUTPUT_DIR: "checkpoints/coco/faster_rcnn/finetune_pseudo_30shot"

